/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.LoginController;
import models.Employees;
import models.EmployeesDao;

/**
 *
 * @author carje
 */
public class LoginView extends javax.swing.JFrame {

    Employees employee = new Employees();
    EmployeesDao employee_dao = new EmployeesDao();
    
    public LoginView() {
        initComponents();//si no se coloca, no se inician los componentes del JFrame
        //controlador del login
        LoginController employee_login = new LoginController(employee,employee_dao,this);
        setSize(930,415);//definimos el tamaño
        setResizable(false);// que no puedan cambiar el tamaño
        setTitle("Ingresar al sistema"); //definimos el titulo del panel
        setLocationRelativeTo(null); //Para que no permitan ubicar la pantalla en otro sitio
        this.repaint(); // Para que los cambios se apliquen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_enter = new javax.swing.JButton();
        txt_wrong_password = new javax.swing.JLabel();
        txt_user_null = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 147, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INICIAR SESIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 67, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 210, 35));

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 210, 35));

        btn_enter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_enter.setText("Ingresar");
        btn_enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 210, 35));

        txt_wrong_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_wrong_password.setForeground(new java.awt.Color(255, 204, 204));
        txt_wrong_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_wrong_password.setText("Usuario o contraseña incorrecta");
        jPanel1.add(txt_wrong_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 220, 30));

        txt_user_null.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_user_null.setForeground(new java.awt.Color(255, 204, 204));
        txt_user_null.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_user_null.setText("¡Escriba usuario y contraseña!");
        jPanel1.add(txt_user_null, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 490, 420));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/interior-de-farmacia-moderno-con-visitante-pedido-cliente-y-compra-del-medicamentos-farmacéutico-pie-en-el-mostrador-uniforme-180878826.jpg"))); // NOI18N
        jPanel2.add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 410));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 412));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPasswordField txt_password;
    public javax.swing.JLabel txt_user_null;
    public javax.swing.JTextField txt_username;
    public javax.swing.JLabel txt_wrong_password;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
